//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operatore : Utente
    {
        public Operatore()
        {
            this.TicketAssegnati = new HashSet<Ticket>();
            this.CambiStato = new HashSet<CambioStato>();
        }
    
    
        public virtual ICollection<Ticket> TicketAssegnati { get; set; }
        public virtual ICollection<CambioStato> CambiStato { get; set; }
        public virtual LivelloOperatore Livello { get; set; }
    }
}
