//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Applicativo
    {
    
    
        [Required]
        public int Id { get; set; }
    
    
        /// <summary>
        /// : codice dell'appllicativo e deve essere uguale a quello dei vari progetti installati (es. ADM, CLK, SUP, )
        /// </summary>
    	[StringLength(10)]
        [Required]
        public string Codice { get; set; }
    
    
    	[StringLength(255)]
        [Required]
        public string Descrizione { get; set; }
    }
}
