//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ruolo
    {
        public Ruolo()
        {
            this.RuoloGruppoUtente = new HashSet<RuoloGruppoUtente>();
            this.RuoloUtenteForced = new HashSet<RuoloUtenteForced>();
        }
    
    
    
        [Required]
        public int RuoloId { get; set; }
    
    
        [Required]
        public int ApplicativoId { get; set; }
    
    
    	[StringLength(10)]
        [Required]
        public string Codice { get; set; }
    
    
    	[StringLength(255)]
        [Required]
        public string Descrizione { get; set; }
    
        public virtual Applicativo Applicativo { get; set; }
        public virtual ICollection<RuoloGruppoUtente> RuoloGruppoUtente { get; set; }
        public virtual ICollection<RuoloUtenteForced> RuoloUtenteForced { get; set; }
    }
}
