//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RuoloGruppoUtente
    {
    
    
        [Required]
        public int RuoloId { get; set; }
    
    
        [Required]
        public int ApplicativoId { get; set; }
    
    
        [Required]
        public short GRP_ID { get; set; }
    
        public virtual Ruolo Ruolo { get; set; }
        public virtual V_ESSE3_GRUPPI_UTENTE V_ESSE3_GRUPPI_UTENTE { get; set; }
    }
}
