//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.CambiStato = new HashSet<CambioStato>();
        }
    
        public int Id { get; set; }
        public string Titolo { get; set; }
        public string Descrizione { get; set; }
        public System.DateTime Creazione { get; set; }
        public System.DateTime Aggiornamento { get; set; }
    
        public virtual Utente Autore { get; set; }
        public virtual Operatore Operatore { get; set; }
        public virtual ICollection<CambioStato> CambiStato { get; set; }
    }
}
