//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserProfilerContext : DbContext
    {
        public UserProfilerContext()
            : base("name=UserProfilerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
    	/// <summary>
        /// :  elenca tutti gli applicativi (admissions, clickr, etc.) il cui codice deve corrispondere agli applicativi chiamanti
        /// </summary>
        public IDbSet<Applicativo> UPR_APPLICATIVI { get; set; }
    
        public IDbSet<Utente> V_UTENTI { get; set; }
    
        public IDbSet<V_ESSE3_UTENTI> V_ESSE3_UTENTI { get; set; }
    
        public IDbSet<V_ESSE3_GRUPPI_UTENTE> V_ESSE3_GRUPPI_UTENTE { get; set; }
    
        public IDbSet<Ruolo> UPR_RUOLI { get; set; }
    
        public IDbSet<RuoloUtenteForced> UPR_RUOLI_UTE_FORCED { get; set; }
    
        public IDbSet<RuoloGruppoUtente> UPR_RUOLI_GRP_UTE { get; set; }
    }
}
