//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Default : DbContext
    {
        public Default()
            : base("name=Default")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ticket> TicketSet { get; set; }
        public DbSet<CambioStato> CambioStatoSet { get; set; }
        public DbSet<Utente> UtenteSet { get; set; }
        public DbSet<LivelloOperatore> LivelloOperatoreSet { get; set; }
    }
}
