//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfiler.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class V_ESSE3_GRUPPI_UTENTE
    {
        public V_ESSE3_GRUPPI_UTENTE()
        {
            this.RuoloGruppoUtente = new HashSet<RuoloGruppoUtente>();
        }
    
    
    
        [Required]
        public short GRP_ID { get; set; }
    
    
    	[StringLength(20)]
        public string GRP_NAME { get; set; }
    
    
        [Required]
        public short AUTH_PWD_MASTER_LOCATION { get; set; }
    
        public virtual ICollection<RuoloGruppoUtente> RuoloGruppoUtente { get; set; }
    }
}
